### PR TITLE
add height for correctly displaying on real mobile devices

### PR DESCRIPTION
**Pull request by MateuszLisowski**
## Related Issue
https://github.com/gautamkrishnar/nothing-private/issues/55

## How Has This Been Tested?
Was tested via Browserstack on different mobile devices

## Screenshots (if appropriate):
Before:
screen shot 2019-01-07 at 23 20 32

After:
screen shot 2019-01-07 at 23 21 00

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@MateuszLisowski Thanks a lot for the PR 🎉

**Comment by gautamkrishnar** [comment]
@MateuszLisowski Please add the PR to https://issuehunt.io/repos/76684607/issues/55 to get your 10$ reward. 😄

**Comment by MateuszLisowski** [comment]
@gautamkrishnar Thanks, URL added :)

**Comment by gautamkrishnar** [comment]
@MateuszLisowski funds released. 🎉

**Pull request merged**
