### PR TITLE
Notes url changed and notes changed 

### PR DESCRIPTION
**Pull request by awaisrafiq410**
Added Firefox 69.0.1 as a secure browser

I'm testing Firefox because it resists fingerprinting by default. 

## Description

There is nothing to do. All you have to do is download firefox 69.0.0 or above.
## Motivation and Context

It is easy for every user.
## How Has This Been Tested?

I checked it and I think it is complete and looks quite good
## Screenshots (if appropriate):
start_page
see_megic
final_test

### CODE REVIEW

**Comment by awaisrafiq410** [comment]
Added firefox as a secure browser also added notes.

**Comment by gautamkrishnar** [comment]
Screenshot 2019-10-03 at 3 28 09 PM
I am unable to reproduce this on browser. Hence closing this. The browsers listed in the safe browsers list must be fully safe to use across all the platforms. Thanks for contributing.

**Comment by awaisrafiq410** [comment]
I don't know the reason behind this but I tried 2nd time on a different laptop and smae results came.

image

image

**Comment by awaisrafiq410** [comment]
Mark this as valid PR.

**Comment by gautamkrishnar** [comment]
@awaisrafiq410 Really sorry,  I am not sure why its working for you. Can't reproduce this behavior on my web browser. It cannot be accepted since it is not globally reproducible.

**Pull request closed without merging**
